<?php

namespace Database\Seeders;

use App\Models\Socio;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SociosSeeder extends Seeder
{
    public function run(): void
    {
        $socios = [
            ['legajo' => 3187, 'nombre' => 'ADRIAN MAXIMILIANO ABRAHAM', 'correo' => 'lauybren@hotmail.com'],
            ['legajo' => 3695, 'nombre' => 'ALEJANDRO VICTORIO ABREGO', 'correo' => 'victorioabrego587@gmail.com'],
            ['legajo' => 3741, 'nombre' => 'JOSE DANIEL ACOSTA', 'correo' => 'rosset.patricia2@gmail.com'],
            ['legajo' => 4099, 'nombre' => 'RUBEN DARIO ACOSTA', 'correo' => 'ar3817983@gmail.com'],
            ['legajo' => 3861, 'nombre' => 'GERMAN ANDRES AGUER', 'correo' => 'germand931@gmail.com'],
            ['legajo' => 4114, 'nombre' => 'GONZALO EZEQUIEL AGUILAR', 'correo' => 'guadam20.06.2016@gmail.com'],
            ['legajo' => 4146, 'nombre' => 'HUGO ALBERTO AGUILAR', 'correo' => 'hugoalbertoaguilar08@gmail.com'],
            ['legajo' => 4147, 'nombre' => 'JESUS MIGUEL ANGEL ALBORNOZ', 'correo' => 'jesusmiguelangel18@gmail.com'],
            ['legajo' => 4143, 'nombre' => 'FERNANDO DANIEL ALMADA', 'correo' => 'fernandoalmada0912@gmail.com'],
            ['legajo' => 4124, 'nombre' => 'LUCAS MARTÍN ALVAREZ VARELA', 'correo' => 'chupete444@hotmail.com'],
            ['legajo' => 3629, 'nombre' => 'ADOLFO ARIEL ARCE', 'correo' => 'ariarce10@hotmail.com'],
            ['legajo' => 4141, 'nombre' => 'ADRIAN ALEXANDER JONATAN ARRIONDO', 'correo' => 'adrianarriondo6@gmail.com'],
            ['legajo' => 3729, 'nombre' => 'JOSE MAXIMILIANO BACHINI', 'correo' => 'josemaximilianobachini@gmail.com'],
            ['legajo' => 4044, 'nombre' => 'GONZALO JESUS MARIA BALTA', 'correo' => 'gonzalobalta147@gmail.com'],
            ['legajo' => 4092, 'nombre' => 'ABELARDO JORGE BANEGA', 'correo' => 'locolito63@gmail.com'],
            ['legajo' => 4118, 'nombre' => 'JOSE ANGEL GABRIEL BARDUIL', 'correo' => 'barduiljoseangelgabriel@gmail.com'],
            ['legajo' => 3191, 'nombre' => 'CARLOS OSVALDO BARRETO', 'correo' => 'barretocarlos1965@hotmail.com'],
            ['legajo' => 3780, 'nombre' => 'CRISTIAN MIGUEL BARZOLA', 'correo' => 'cristianbarzola76@gmail.com'],
            ['legajo' => 4131, 'nombre' => 'CARLOS RAMON BELLO', 'correo' => 'bellocarlos1971@gmail.com'],
            ['legajo' => 3984, 'nombre' => 'SERGIO ORLANDO BELTZER', 'correo' => 'orlando-beltzer@live.com.ar'],
            ['legajo' => 4086, 'nombre' => 'CRISTIAN LEANDRO BENEDETICH', 'correo' => 'cristianbenedetich@gmail.com'],
            ['legajo' => 4058, 'nombre' => 'ERIC NAHUEL BENEDETICH', 'correo' => 'ericbeby210895@gmail.com'],
            ['legajo' => 3369, 'nombre' => 'JUAN CARLOS BENITEZ', 'correo' => 'juancbenitez0415@gmail.com'],
            ['legajo' => 4102, 'nombre' => 'JULIAN CRUZ BERLARI', 'correo' => 'juliancruzberlari37@gmail.com'],
            ['legajo' => 3306, 'nombre' => 'MARIANO SEBASTIAN BERTOLI', 'correo' => 'bertolibertoli86@gmail.com'],
            ['legajo' => 3883, 'nombre' => 'LEONARDO MAURO BIGLIARDI', 'correo' => 'lbigliardi@hotmail.com'],
            ['legajo' => 4108, 'nombre' => 'JAVIER EDUARDO BORDON', 'correo' => 'javiereduardobordon@gmail.com'],
            ['legajo' => 3100, 'nombre' => 'MARCELO OMAR BORDON', 'correo' => 'bordonmarcelo431@gmail.com'],
            ['legajo' => 4126, 'nombre' => 'MILTON OSCAR BOTTO', 'correo' => 'miltonbotto339@gmail.com'],
            ['legajo' => 3057, 'nombre' => 'PAULINO RICARDO CABAÑA', 'correo' => 'ricardocabana60@gmail.com'],
            ['legajo' => 4010, 'nombre' => 'CARLOS ROMAN CABRERA', 'correo' => 'carlosromancabrera@gmail.com'],
            ['legajo' => 3295, 'nombre' => 'SILVIO FABIAN CABRERA', 'correo' => 'fabielnegro08@gmail.com'],
            ['legajo' => 3796, 'nombre' => 'DIEGO RUBEN CAÑETE', 'correo' => 'diegolavieja28@gmail.com'],
            ['legajo' => 3460, 'nombre' => 'OSCAR HECTOR FABIAN CARDOSO', 'correo' => 'oscarhectorfabiancardozo@gmail.com'],
            ['legajo' => 3125, 'nombre' => 'MATIAS DANIEL CARRERE', 'correo' => 'djmatrus@hotmail.com'],
            ['legajo' => 4130, 'nombre' => 'BRIAN EXEQUIEL CASCO', 'correo' => 'djpeericler35@gmail.com'],
            ['legajo' => 3365, 'nombre' => 'ANGEL ENRIQUE CASTAÑO', 'correo' => 'angelenriquecasta@gmail.com'],
            ['legajo' => 3466, 'nombre' => 'DIEGO MARTIN CASTAÑO', 'correo' => 'diegomcastano37@gmail.com'],
            ['legajo' => 3735, 'nombre' => 'VICTOR HUGO CASTAÑO', 'correo' => 'victorcastanio@hotmail.com'],
            ['legajo' => 3591, 'nombre' => 'LUCIANO MARTIN CASTELLETTI', 'correo' => 'luciano.castelletti@hotmail.com'],
            ['legajo' => 3921, 'nombre' => 'OSVALDO ANTONIO CERIANI', 'correo' => 'dani_voley5@hotmail.es'],
            ['legajo' => 4093, 'nombre' => 'GUSTAVO DANIEL CHAVARRIA', 'correo' => 'soleliana_28@hotmail.com'],
            ['legajo' => 4025, 'nombre' => 'MATIAS GONZALO CIARROCCA', 'correo' => 'ciarroccacolo@gmail.com'],
            ['legajo' => 4112, 'nombre' => 'MATIAS LEONARDO CISLAGHI', 'correo' => 'matutecislaghi680@gmail.com'],
            ['legajo' => 3615, 'nombre' => 'LUIS ALBERTO COLONIATTE', 'correo' => 'luisalbertocoloniatte@gmail.com'],
            ['legajo' => 4052, 'nombre' => 'CARLOS JOSE LUIS CORDOBA', 'correo' => 'carloscordobavgm@outlook.com'],
            ['legajo' => 3566, 'nombre' => 'CARLOS ALBERTO CORONEL', 'correo' => 'cac_marcodana@hotmail.com'],
            ['legajo' => 3208, 'nombre' => 'ANDRES ALBERTO CORREA', 'correo' => 'esteliocorrea65@gmail.com'],
            ['legajo' => 4115, 'nombre' => 'ANDRES EZEQUIEL CORREA', 'correo' => 'andrescorrea_28@hotmail.com'],
            ['legajo' => 3209, 'nombre' => 'ESTELIO RAUL CORREA', 'correo' => 'correaestelio@gmail.com'],
            ['legajo' => 3777, 'nombre' => 'HUGO CESAR CORREA', 'correo' => 'hucocorrea75@gmail.com'],
            ['legajo' => 3051, 'nombre' => 'ALEJANDRO GABRIEL CUELLO', 'correo' => 'cohelo_agc@hotmail.com'],
            ['legajo' => 4006, 'nombre' => 'CRISTIAN NICOLAS DEHARBE', 'correo' => 'nicolasdeharbe1@gmail.com'],
            ['legajo' => 4109, 'nombre' => 'JOSE GABRIEL DEHARBE', 'correo' => 'gabideharbe9@gmail.com'],
            ['legajo' => 3827, 'nombre' => 'JOSE IGNACIO DEHARBE', 'correo' => 'josedeharbe84@gmail.com'],
            ['legajo' => 3355, 'nombre' => 'JOSE MARIA DEHARBE', 'correo' => 'josedeharbe81@gmail.com'],
            ['legajo' => 4046, 'nombre' => 'BRUNO DELL ´UNTI', 'correo' => 'bdelunti@gmail.com'],
            ['legajo' => 3611, 'nombre' => 'NORBERTO DARDO DEVEZ', 'correo' => 'estefidevez15@gmail.com'],
            ['legajo' => 4048, 'nombre' => 'CARLOS DAMIAN DIAZ', 'correo' => 'juntoscnj2019@gmail.com'],
            ['legajo' => 4103, 'nombre' => 'CRISTIAN ARIEL DIAZ', 'correo' => 'cd5518706@gmail.com'],
            ['legajo' => 3937, 'nombre' => 'ANGEL MAURICIO DITTLER', 'correo' => 'mauriciodittler@gmail.com'],
            ['legajo' => 4137, 'nombre' => 'ADALBERTO DARIO EBERHARDT', 'correo' => 'darkodae@hotmail.com'],
            ['legajo' => 3640, 'nombre' => 'NORBERTO NICOLAS EBERLE', 'correo' => 'norberto.eberle@hotmail.com'],
            ['legajo' => 3862, 'nombre' => 'RAUL DANIEL EBERLE', 'correo' => 'elraulo3862@gmail.com'],
            ['legajo' => 3826, 'nombre' => 'SERGIO CESAR EMERI', 'correo' => 'sergioemeri@hotmail.com'],
            ['legajo' => 3781, 'nombre' => 'DIEGO OCTAVIO RAFAEL ESPINDOLA', 'correo' => 'daiana.espindola444@gmail.com'],
            ['legajo' => 3367, 'nombre' => 'JOSE ALBERTO ESPINDOLA', 'correo' => 'espindolapico67@outlook.com'],
            ['legajo' => 3731, 'nombre' => 'RICARDO FABIAN ESPINDOLA', 'correo' => 'fespindola276@gmail.com'],
            ['legajo' => 4088, 'nombre' => 'SEBASTIAN FABIAN ESPINDOLA', 'correo' => 'espindolasebastian539@gmail.com'],
            ['legajo' => 3766, 'nombre' => 'JUAN CARLOS FERREYRA', 'correo' => 'juancaferr52@gmail.com'],
            ['legajo' => 3903, 'nombre' => 'RAMON OSVALDO OSCAR FLEITAS', 'correo' => 'fleiosvaldo13@gmail.com'],
            ['legajo' => 3790, 'nombre' => 'HERNAN EDUARDO FLORES', 'correo' => 'rusoflores442@gmail.com'],
            ['legajo' => 3438, 'nombre' => 'FABIAN ALBERTO FONTANA', 'correo' => 'fabianfontana166@gmail.com'],
            ['legajo' => 4047, 'nombre' => 'MARTIN ISIDRO FONTANINI NUÑEZ', 'correo' => 'martin000_7@hotmail.com'],
            ['legajo' => 4105, 'nombre' => 'ANTONIO JOSE FRANCISCONI', 'correo' => 'francisconiantonio4@gmail.com'],
            ['legajo' => 4138, 'nombre' => 'KEVIN ABILIO FRANCO', 'correo' => 'kevin0796franco@gmail.com'],
            ['legajo' => 4129, 'nombre' => 'RICARDO DANIEL FRANCO', 'correo' => 'ricardodanielfranco27@gmail.com'],
            ['legajo' => 3798, 'nombre' => 'RAUL ALBERTO GAITAN', 'correo' => 'albertonano160@gmail.com'],
            ['legajo' => 3877, 'nombre' => 'LEANDRO DANIEL GAMBINO', 'correo' => 'gambinoleandrodaniel379@gmail.com'],
            ['legajo' => 3565, 'nombre' => 'CARLOS DANIEL GARCIA', 'correo' => 'charlydgarcia63@gmail.com'],
            ['legajo' => 4119, 'nombre' => 'EMILIANO DANIEL GARCIA', 'correo' => 'eg108689@gmail.com'],
            ['legajo' => 3406, 'nombre' => 'JORGE ALBERTO GARZON', 'correo' => 'alberto.monchy@gmail.com'],
            ['legajo' => 4076, 'nombre' => 'NELSON SEBASTIAN GERMANA', 'correo' => 'boca221.nsg@gmail.com'],
            ['legajo' => 4039, 'nombre' => 'IVAN EMANUEL GERMANO', 'correo' => 'ivanegermano@gmail.com'],
            ['legajo' => 3405, 'nombre' => 'JUAN CARLOS GHIRINGHELLI', 'correo' => 'juancarlisghiringhelli@gmail.com'],
            ['legajo' => 3567, 'nombre' => 'CARINA CECILIA GILES', 'correo' => 'carina.c.g66@gmail.com'],
            ['legajo' => 3602, 'nombre' => 'ADRIAN JESUS GODOY', 'correo' => 'adrijegodoy@gmail.com'],
            ['legajo' => 4106, 'nombre' => 'MARCELO GABRIEL GODOY', 'correo' => 'marcelogabrielgodoy1@gmail.com'],
            ['legajo' => 3923, 'nombre' => 'OSCAR ANDRES GOMEZ', 'correo' => 'mohamed_10_7@hotmail.com'],
            ['legajo' => 3186, 'nombre' => 'PEDRO LEONARDO GOMEZ', 'correo' => 'leonardopedrogomez@gmail.com'],
            ['legajo' => 3886, 'nombre' => 'CRISTIAN ERNESTO ARIEL GONZALEZ', 'correo' => 'cg20761@gmail.com'],
            ['legajo' => 4032, 'nombre' => 'ELIAS JOSE GONZALEZ', 'correo' => 'eliasgonzales@live.com'],
            ['legajo' => 4097, 'nombre' => 'FACUNDO GASTÓN GONZALEZ', 'correo' => 'barqueroyami185@gmail.com'],
            ['legajo' => 3580, 'nombre' => 'GASTÓN LEONARDO GONZALEZ', 'correo' => 'gayegogonzalez@gmail.com'],
            ['legajo' => 3484, 'nombre' => 'JULIO CESAR GONZALEZ', 'correo' => 'oiluj03@hotmail.com'],
            ['legajo' => 3977, 'nombre' => 'GUSTAVO FABIAN GORDILLO', 'correo' => 'gustavofabiangordillo16@gmail.com'],
            ['legajo' => 3586, 'nombre' => 'STELLA MARIS GRINOVERO', 'correo' => 'stellamarisgrinovero@gmail.com'],
            ['legajo' => 4031, 'nombre' => 'JORGE ALBERTO GUZMAN', 'correo' => 'jorgeg.jg52@gmail.com'],
            ['legajo' => 4151, 'nombre' => 'RODRIGO SEBASTIÁN HAUFF', 'correo' => 'hauffrodrigo21@gmail.com'],
            ['legajo' => 3773, 'nombre' => 'HUGO MARCELO HEFT', 'correo' => 'marceloheft@gmail.com'],
            ['legajo' => 3588, 'nombre' => 'FABIAN EDUARDO HEREÑU', 'correo' => 'fabianvasco220@gmail.com'],
            ['legajo' => 3165, 'nombre' => 'MIGUEL ANGEL HILFER', 'correo' => 'miguel.hilfer@gmail.com'],
            ['legajo' => 4051, 'nombre' => 'GASTON IBARRA', 'correo' => 'ibarragastonazulian@gmail.com'],
            ['legajo' => 3408, 'nombre' => 'EDUARDO AGUSTIN IENCINELLA', 'correo' => 'eduagienci2000@yahoo.com.ar'],
            ['legajo' => 3920, 'nombre' => 'GUILLERMO ISASI', 'correo' => 'guillermoisasi601@gmail.com'],
            ['legajo' => 3376, 'nombre' => 'RICARDO JOSE JACOB', 'correo' => 'ricardojacob0312@gmail.com'],
            ['legajo' => 4127, 'nombre' => 'PABLO DAMIAN JAKOVLJEVIC', 'correo' => 'pdj_elpolaco622@hotmail.com'],
            ['legajo' => 3531, 'nombre' => 'ISIDRO KAMLOFKY', 'correo' => 'ikamlofky@gmail.com'],
            ['legajo' => 3978, 'nombre' => 'FRANCISCO MARIO JESUS KEMMERER', 'correo' => 'franciscokemmerer4@gmail.com'],
            ['legajo' => 4009, 'nombre' => 'NELSON JOSE ROBERTO KEMMERER', 'correo' => 'nelsotenkem13@gmail.com'],
            ['legajo' => 3859, 'nombre' => 'DIEGO JULIAN KOTLIREVSKY', 'correo' => 'keto666.dk@gmail.com'],
            ['legajo' => 3560, 'nombre' => 'FABIAN OSCAR KRAWCZUK', 'correo' => 'fkrawczuk@hotmail.com'],
            ['legajo' => 3634, 'nombre' => 'ALEJANDRO JAVIER LALLANA', 'correo' => 'lallanajavier@gmail.com'],
            ['legajo' => 3206, 'nombre' => 'JOSE LUIS LALLANA', 'correo' => 'lallanajoseluis20@gmail.com'],
            ['legajo' => 3296, 'nombre' => 'SERGIO FABIAN LALLANA', 'correo' => 'sergiofabianlallsna@gmail.com'],
            ['legajo' => 4060, 'nombre' => 'WALTER DAVID LALLANA', 'correo' => 'w_altr@hotmail.com'],
            ['legajo' => 4132, 'nombre' => 'ALAN NICOLAS LEAL', 'correo' => 'lealalan212@gmail.com'],
            ['legajo' => 4043, 'nombre' => 'ANGEL FABIAN LECHMAN', 'correo' => 'lechmanguadalupe@gmail.com'],
            ['legajo' => 4140, 'nombre' => 'LUCAS LEDESMA', 'correo' => 'ledesma.lucas0602@gmail.com'],
            ['legajo' => 3573, 'nombre' => 'CLAUDIO GUSTAVO LEGOFF', 'correo' => 'claudiolegoff08@gmail.com'],
            ['legajo' => 4148, 'nombre' => 'PABLO EMANUEL LEIVA', 'correo' => 'leivapabloemanuel22@gmail.com'],
            ['legajo' => 3752, 'nombre' => 'GUSTAVO DAMIAN LEONARDT', 'correo' => 'gustavoleonardt@yahoo.com.ar'],
            ['legajo' => 4113, 'nombre' => 'ADRIEL LAUREANO LEONHARDT', 'correo' => 'leonhardtlaureano@gmail.com'],
            ['legajo' => 3999, 'nombre' => 'ANGEL GABRIEL LESCANO', 'correo' => 'angelgabrielescano@gmail.com'],
            ['legajo' => 3321, 'nombre' => 'HUGO PABLO LONDERO', 'correo' => 'marianlondero@gmail.com'],
            ['legajo' => 3201, 'nombre' => 'AMERICO OSVALDO LOPEZ', 'correo' => 'osvaldolopezpata@gmail.com'],
            ['legajo' => 3431, 'nombre' => 'JORGE EDUARDO LOPEZ', 'correo' => 'lopezjorge5268@gmail.com'],
            ['legajo' => 3738, 'nombre' => 'CLAUDIO ALEJANDRO LUNA', 'correo' => 'claudioluna728@gmail.com'],
            ['legajo' => 3004, 'nombre' => 'JESUS NICOLAS RAMON MACIEL', 'correo' => 'jesflor26@gmail.com'],
            ['legajo' => 3601, 'nombre' => 'LUIS ANGEL MANDELLI', 'correo' => 'luislm196407@gmail.com'],
            ['legajo' => 4136, 'nombre' => 'JOSIAS EDUARDO MANSILLA ANELLO', 'correo' => 'jmansillaanello@gmail.com'],
            ['legajo' => 4073, 'nombre' => 'LUCIANO DANIEL MARAÑON', 'correo' => 'maranon_luciano@hotmail.com'],
            ['legajo' => 3857, 'nombre' => 'ALEJANDRO FEDERICO MARTINEZ', 'correo' => 'amartinezpna@gmail.com'],
            ['legajo' => 3558, 'nombre' => 'FERNANDO GUILLERMO MARTINEZ', 'correo' => 'fernandogmartinez8164@gmail.com'],
            ['legajo' => 3821, 'nombre' => 'WALTER EDGARDO MARTINEZ', 'correo' => 'walteremartinez76@gmail.com'],
            ['legajo' => 4019, 'nombre' => 'EMILIO EUGENIO MARZOCCHI', 'correo' => 'emiliomarzocchi11@gmail.com'],
            ['legajo' => 3401, 'nombre' => 'NORBERTO RICARDO MAYER', 'correo' => 'beto-mayer@hotmail.com'],
            ['legajo' => 3200, 'nombre' => 'DIEGO HERNAN MEDICI', 'correo' => 'hernanmedici10@gmail.com'],
            ['legajo' => 4041, 'nombre' => 'MARIO MAURICIO MEDINA', 'correo' => 'mauromedina722@gmail.com'],
            ['legajo' => 4034, 'nombre' => 'DIEGO FEDERICO MEHRER', 'correo' => 'mehrerdiego33@gmail.com'],
            ['legajo' => 3481, 'nombre' => 'DIEGO MARTIN ALEJANDRO MENA', 'correo' => 'diegomena349@gmail.com'],
            ['legajo' => 3554, 'nombre' => 'MARIA EUGENIA MENDEZ', 'correo' => 'eugemendez320@gmail.com'],
            ['legajo' => 4111, 'nombre' => 'NICOLAS LEANDRO MIGONI', 'correo' => 'teoomar872@gmail.com'],
            ['legajo' => 4011, 'nombre' => 'LEONARDO SEBASTIAN MINIGUTTI', 'correo' => 'lyon77@outlook.com'],
            ['legajo' => 3782, 'nombre' => 'ANGEL JESUS MOINE', 'correo' => 'moineangel@gmail.com'],
            ['legajo' => 4133, 'nombre' => 'ROLANDO JAVIER MOLINA', 'correo' => 'rolymolinacc@gmail.com'],
            ['legajo' => 4089, 'nombre' => 'PEDRO NICOLAS MONTERO', 'correo' => 'monteronicolas053@gmail.com'],
            ['legajo' => 3075, 'nombre' => 'SERGIO OSCAR MONTERO', 'correo' => 'monterosergio889@gmail.com'],
            ['legajo' => 4062, 'nombre' => 'ADRIAN EMANUEL MORALES', 'correo' => 'adrianmoralez9988@gmail.com'],
            ['legajo' => 4142, 'nombre' => 'SANTIAGO IVAN MOREL', 'correo' => 'santiagoeladio2021@gmail.com'],
            ['legajo' => 3593, 'nombre' => 'PABLO ARIEL MUÑOZ', 'correo' => 'munoz.pabloa51@gmail.com'],
            ['legajo' => 3594, 'nombre' => 'RODRIGO JESUS NANI', 'correo' => 'rodrigonanitecnica@gmail.com'],
            ['legajo' => 3867, 'nombre' => 'CHRISTIAN EDUARDO NAVARRO', 'correo' => 'peladonavar302@gmail.com'],
            ['legajo' => 4128, 'nombre' => 'ENZO GABRIEL NIETO', 'correo' => 'enzogabriel3099@gmail.com'],
            ['legajo' => 3294, 'nombre' => 'JOSE ADRIAN NIETO', 'correo' => 'adrian5nieto1972@gmail.com'],
            ['legajo' => 3799, 'nombre' => 'HECTOR FRANCISCO OCAMPO', 'correo' => 'ocampocuchi@hotmail.com'],
            ['legajo' => 3436, 'nombre' => 'NESTOR RAUL ORMACHE', 'correo' => 'eliormache@gmail.com'],
            ['legajo' => 3109, 'nombre' => 'PEDRO MARTIN ORMACHE', 'correo' => 'pedromartinormache@gmail.com'],
            ['legajo' => 3116, 'nombre' => 'RODRIGO MARTIN ORMACHE', 'correo' => 'rodrigonesta@yahoo.com'],
            ['legajo' => 3880, 'nombre' => 'FERNANDO ARIEL RAMON OTERO', 'correo' => 'fernandootero156@gmail.com'],
            ['legajo' => 4139, 'nombre' => 'PABLO NICOLAS PAEZ', 'correo' => 'pablopaez4139@gmail.com'],
            ['legajo' => 3864, 'nombre' => 'VICTOR ARIEL PANNUTO PACHER', 'correo' => 'arielpannuto@gmail.com'],
            ['legajo' => 4134, 'nombre' => 'KEVIN ALEJANDRO PAZ', 'correo' => '125bizpaz@gmail.com'],
            ['legajo' => 3912, 'nombre' => 'CARLOS ALBERTO PENAU', 'correo' => 'penauualberto@gmail.com'],
            ['legajo' => 3760, 'nombre' => 'CLAUDIO ALBERTO PEREIRA', 'correo' => 'aquiri22@hotmail.com'],
            ['legajo' => 3990, 'nombre' => 'CARLOS ALBERTO PEREYRA', 'correo' => 'albert4614@gmail.com'],
            ['legajo' => 4110, 'nombre' => 'ESTEBAN EMANUEL PEREYRA', 'correo' => 'pereyraemanuel515@gmail.com'],
            ['legajo' => 3889, 'nombre' => 'RUBEN DARIO PEREYRA', 'correo' => 'pereyrarubendario454@gmail.com'],
            ['legajo' => 3476, 'nombre' => 'JOEL SEBASTIÁN PEREZ', 'correo' => 'perezjoels29@gmail.com'],
            ['legajo' => 3087, 'nombre' => 'RICARDO DANIEL PEREZ', 'correo' => 'caryperez64@hotmail.com'],
            ['legajo' => 3688, 'nombre' => 'GABRIEL HECTOR OSVALDO PETERSEN', 'correo' => 'petersengabriel860@gmail.com'],
            ['legajo' => 3144, 'nombre' => 'HUGO JULIO PETERSEN', 'correo' => 'hugocabjp@gmail.com'],
            ['legajo' => 3693, 'nombre' => 'MARTIN OSCAR PETERSEN', 'correo' => 'martu1974@gmail.com'],
            ['legajo' => 3495, 'nombre' => 'JORGE JOSE PIACENZA', 'correo' => 'jorgepiacenza881@gmail.com'],
            ['legajo' => 4024, 'nombre' => 'SEBASTIAN EMANUEL PROSS', 'correo' => 'sebastianpross22@gmail.com'],
            ['legajo' => 3879, 'nombre' => 'EZEQUIEL EDUARDO QUIÑONES', 'correo' => 'coloradito45@gmail.com'],
            ['legajo' => 3871, 'nombre' => 'PABLO MATIAS QUINTANA', 'correo' => 'pablomatias_q@hotmail.com'],
            ['legajo' => 4120, 'nombre' => 'ERIC DAMIAN LEONEL RAMIREZ', 'correo' => 'eric1122ramirez@gmail.com'],
            ['legajo' => 3964, 'nombre' => 'DANIEL EDUARDO RETAMAL', 'correo' => 'retamald073@gmail.com'],
            ['legajo' => 3692, 'nombre' => 'JORGE ALBERTO RETAMAL', 'correo' => 'chacho.300@hotmail.com'],
            ['legajo' => 3969, 'nombre' => 'SEBASTIAN RETAMAL', 'correo' => 'sebastianretamal1234@gmail.com'],
            ['legajo' => 4145, 'nombre' => 'JONATHAN ALBERTO RETAMAR', 'correo' => 'retamarjonathan95@gmail.com'],
            ['legajo' => 3302, 'nombre' => 'DAMIAN ERNESTO RIOS', 'correo' => 'damianrios547@gmail.com'],
            ['legajo' => 3159, 'nombre' => 'EDUARDO ESTEBAN RIOS', 'correo' => 'erios4354@gmail.com'],
            ['legajo' => 4149, 'nombre' => 'GASTON NICOLAS RIQUELME', 'correo' => 'gaston19riquelme@gmail.com'],
            ['legajo' => 4123, 'nombre' => 'JUAN IGNACIO RIQUELME', 'correo' => 'jr537137@gmail.com'],
            ['legajo' => 3759, 'nombre' => 'CLAUDIO DANIEL RODRIGUEZ', 'correo' => 'guito.rodriguez09@gmail.com'],
            ['legajo' => 3025, 'nombre' => 'OSCAR DANIEL RODRIGUEZ', 'correo' => 'oscarrodriguez12071959@gmail.com'],
            ['legajo' => 3127, 'nombre' => 'VICTOR ALBERTO RODRIGUEZ', 'correo' => 'victoralbertorod@gmail.com'],
            ['legajo' => 3726, 'nombre' => 'EDUARDO ARIEL ROMERO', 'correo' => 'eduarirome.er@gmail.com'],
            ['legajo' => 3010, 'nombre' => 'RICARDO ANIBAL ROMERO', 'correo' => 'anirikrom@hotmail.com'],
            ['legajo' => 3441, 'nombre' => 'OSCAR ANTONIO ROSKOPF', 'correo' => 'oscarroskopf234@gmail.com'],
            ['legajo' => 4054, 'nombre' => 'CARLOS FRANCISCO ROSSET', 'correo' => 'rossetecarlosf@gmail.com'],
            ['legajo' => 4069, 'nombre' => 'SANTIAGO ALEJANDRO SCHONFELD', 'correo' => 'schonfeldsantiago52@gmail.com'],
            ['legajo' => 4059, 'nombre' => 'MARIANO EUGENIO SIEBER', 'correo' => 'marianitosieber4@gmail.com'],
            ['legajo' => 3774, 'nombre' => 'LEANDRO LEONEL SOMER', 'correo' => 'lean3774@gmail.com'],
            ['legajo' => 3863, 'nombre' => 'GUALBERTO GERMAN SOSA', 'correo' => 'sosagualberto@gmail.com'],
            ['legajo' => 4053, 'nombre' => 'HERNAN MARCELO SOSA', 'correo' => 'mar_cielo217@hotmail.com'],
            ['legajo' => 3119, 'nombre' => 'RAUL OSCAR STABILE', 'correo' => 'raulstabile8@gmail.com'],
            ['legajo' => 4144, 'nombre' => 'ABEL SUAREZ ARREDONDO', 'correo' => 'abelsuarez148@gmail.com'],
            ['legajo' => 3858, 'nombre' => 'WALTER GABRIEL TABLADA', 'correo' => 'walt3rrr@gmail.com'],
            ['legajo' => 3697, 'nombre' => 'JUAN CARLOS TABORDA', 'correo' => 'juancarlostaborda2019@gmail.com'],
            ['legajo' => 3604, 'nombre' => 'NORBERTO JESUS MARIA TABORDA', 'correo' => 'tabordanorberto1988@hotmail.com'],
            ['legajo' => 3997, 'nombre' => 'SERGIO ALFREDO TABORDA', 'correo' => 'k_chuno18@hotmail.com'],
            ['legajo' => 3685, 'nombre' => 'JESUS CARLOS TOLEDO', 'correo' => 'toledo2015169@gmail.com'],
            ['legajo' => 3167, 'nombre' => 'ANIBAL ISMAEL TORRES', 'correo' => 'anibalismatorres@gmail.com'],
            ['legajo' => 3844, 'nombre' => 'HUGO ORLANDO TRONCOSO', 'correo' => 'hugotroncoso15@gmail.com'],
            ['legajo' => 3085, 'nombre' => 'MARIO ANGEL TROPINI', 'correo' => 'mariotropini25@gmail.com'],
            ['legajo' => 3220, 'nombre' => 'RODOLFO LUIS URICH', 'correo' => 'celiasauer0@gmail.com'],
            ['legajo' => 3585, 'nombre' => 'CARLOS LUJAN VALLORI', 'correo' => 'vallori.carlos@gmail.com'],
            ['legajo' => 3589, 'nombre' => 'DANIEL NICOLAS VARRONE', 'correo' => 'nicovarrone@hotmail.es'],
            ['legajo' => 3550, 'nombre' => 'JUAN PEDRO VARRONE', 'correo' => 'juanvarrone2010@gmail.com'],
            ['legajo' => 3350, 'nombre' => 'JULIO ALBERTO VAYU', 'correo' => 'juliovayucai60@gmail.com'],
            ['legajo' => 3115, 'nombre' => 'GUSTAVO DANIEL VERGARA', 'correo' => 'pelado_gustavo@hotmail.com'],
            ['legajo' => 4122, 'nombre' => 'AXEL MARTIN VERNACKT', 'correo' => 'vernacktaxel20@gmail.com'],
            ['legajo' => 4150, 'nombre' => 'NICOLAS CECILIO VERON', 'correo' => 'nicolasveron80s@gmail.com'],
            ['legajo' => 3609, 'nombre' => 'SERGIO RENE VILLAGRA', 'correo' => 'villagrasvmotos@gmail.com'],
            ['legajo' => 4125, 'nombre' => 'MARIANO DAVID VILLALBA', 'correo' => 'villalbadavid560@gmail.com'],
            ['legajo' => 4068, 'nombre' => 'NESTOR ARIEL VILLALBA', 'correo' => 'nestorarvillalba@gmail.com'],
            ['legajo' => 3596, 'nombre' => 'MAXIMILIANO LUIS VILLANUEVA', 'correo' => 'max_03_22@hotmail.com.ar'],
            ['legajo' => 4074, 'nombre' => 'JONATHAN DAVID VISMARA', 'correo' => 'jonathanvismara14@gmail.com'],
            ['legajo' => 3581, 'nombre' => 'DIEGO MARTÍN VITTONE', 'correo' => 'diegomvittone@hotmail.com'],
            ['legajo' => 3330, 'nombre' => 'NESTOR RENE RAMON WERNER', 'correo' => 'werneragustina@hotmail.com'],
            ['legajo' => 3384, 'nombre' => 'OMAR JORGE WERNER', 'correo' => 'eichmangladis@gmail.com'],
            ['legajo' => 3448, 'nombre' => 'DANIEL ENRIQUE ZABALA', 'correo' => 'zabalad901@gmail.com'],
            ['legajo' => 3689, 'nombre' => 'CRISTIAN GABRIEL ZARATE', 'correo' => 'cristianzarate240373@hotmail.com'],
            ['legajo' => 3113, 'nombre' => 'EMANUEL GUSTAVO ZUIANI', 'correo' => 'emanuelgzuiani@gmail.com'],
            ['legajo' => 3804, 'nombre' => 'JUAN PABLO ANTONIO ZUIANI', 'correo' => 'j.pablo2010@hotmail.com'],
            ['legajo' => 3546, 'nombre' => 'SERGIO EDUARDO BUSTAMANTE', 'correo' => 'bustamante.se@gmail.com'],
            ['legajo' => 677, 'nombre' => 'AGUSTIN CARPIO', 'correo' => 'carpio.agustin@ymail.com'],
            ['legajo' => 4707, 'nombre' => 'GUSTAVO NORBERTO GIMENEZ', 'correo' => 'ggimenez@longvie.com.ar'],
            ['legajo' => 4705, 'nombre' => 'GUIDO RODOLFO MULLER', 'correo' => 'guidormuller@gmail.com'],
            ['legajo' => 3564, 'nombre' => 'MARCELO JAVIER RUFANACHT', 'correo' => 'mrufanacht@longvie.com.ar'],
            // ['legajo' => 456, 'nombre' => 'MARIA PAZ KAMLOFKY', 'correo' => 'pazkam@gmail.com'],
            // ['legajo' => 123, 'nombre' => 'LUCIANO NAHUEL ZAPATA', 'correo' => 'luciano.zapata314@gmail.com'],

        ];



        // Eliminar todos los registros existentes



        foreach ($socios as $socio) {
            Socio::create([
                'legajo' => $socio['legajo'],
                'nombre' => $socio['nombre'],
                'correo' => $socio['correo'],
                'created_at' => now(),

            ]);
        }
    }
}
