export interface Liquidacion {
  legajo: number
  socioNombre: string
  cuota: number
  ss_adm: number
  fcia_maria_luisa: number
  fcia_amur: number
  fcia_la_botica: number
  oseca: number
  villegas: number
  luz_y_fza: number
  flama: number
  fontana: number
  moto_city: number
  transporte: number
  mutual_sol: number
  viandas: number
  seguro: number
  uso_ins_cd: number
  cantina_cd: number
  varios_bebidas: number
  prestamos: number
  interes_prestamos: number
  saldo: number
  interes_saldo: number
  campera: number
  asado: number
  torno_pezca: number
  sofia_shop: number
  cant_metal: number
  sub_total: number
  gasto_bancario: number
  total: number
}
