export const columnas = [
  { key: 'cuota', label: 'Cuota' },
  { key: 'ss_adm', label: 'SS Adm' },
  { key: 'fcia_maria_luisa', label: 'Fcia M. Luisa' },
  { key: 'fcia_amur', label: 'Fcia Amur' },
  { key: 'fcia_la_botica', label: 'Fcia La Botica' },
  { key: 'oseca', label: 'OSECA' },
  { key: 'villegas', label: 'Villegas' },
  { key: 'luz_y_fza', label: 'Luz y Fza' },
  { key: 'flama', label: 'Flama' },
  { key: 'fontana', label: 'Fontana' },
  { key: 'moto_city', label: 'Moto City' },
  { key: 'transporte', label: 'Transporte' },
  { key: 'mutual_sol', label: 'Mutual Sol' },
  { key: 'viandas', label: 'Viandas' },
  { key: 'seguro', label: 'Seguro' },
  { key: 'uso_ins_cd', label: 'Uso Ins CD' },
  { key: 'cantina_cd', label: 'Cantina CD' },
  { key: 'saldo', label: 'Saldo' },
  { key: 'interes_saldo', label: 'Interés Saldo' },
  { key: 'sub_total', label: 'Subtotal' },
  { key: 'gasto_bancario', label: 'G. Bancario' },
  { key: 'total', label: 'Total' }
]
