export const columnas = [
  { key: 'cuota', label: 'Cuota' },
  { key: 'ss_adm', label: 'SS Adm' },
  { key: 'fcia_maria_luisa', label: 'Fcia M. Luisa' },
  { key: 'fcia_amur', label: 'Fcia Amur' },
  { key: 'fcia_la_botica', label: 'Fcia La Botica' },
  { key: 'oseca', label: 'OSECA' },
  { key: 'villegas', label: 'Villegas' },
  { key: 'luz_y_fza', label: 'Luz y Fza' },
  { key: 'flama', label: 'Flama' },
  { key: 'fontana', label: 'Fontana' },
  { key: 'moto_city', label: 'Moto City' },
  { key: 'transporte', label: 'Transporte' },
  { key: 'mutual_sol', label: 'Mutual Sol' },
  { key: 'viandas', label: 'Viandas' },
  { key: 'seguro', label: 'Seguro' },
  { key: 'uso_ins_cd', label: 'Uso Ins CD' },
  { key: 'varios_bebidas', label: 'Varios - Bebidas' },
  { key: 'prestamos', label: 'Préstamos' },
  { key: 'interes_prestamos', label: 'Interés Préstamos' },
  { key: 'cantina_cd', label: 'Cantina CD' },
  { key: 'saldo', label: 'Saldo' },
  { key: 'interes_saldo', label: 'Interés Saldo' },
  { key: 'campera', label: 'Campera' },
  { key: 'asado', label: 'Asado' },
  { key: 'torno_pezca', label: 'Torno Pezca' },
  { key: 'sofia_shop', label: 'Sofia Shop' },
  { key: 'cant_metal', label: 'Cant Metal' },
  { key: 'sub_total', label: 'Subtotal' },
  { key: 'gasto_bancario', label: 'G. Bancario' },
  { key: 'total', label: 'Total' }
]

export const campos = [
  'cuota',
  'ss_adm',
  'fcia_maria_luisa',
  'fcia_amur',
  'fcia_la_botica',
  'oseca',
  'villegas',
  'luz_y_fza',
  'flama',
  'fontana',
  'moto_city',
  'transporte',
  'mutual_sol',
  'viandas',
  'seguro',
  'uso_ins_cd',
  'cantina_cd',
  'saldo',
  'interes_saldo',
  'campera',
  'asado',
  'torno_pezca',
  'sofia_shop',
  'cant_metal',
  'sub_total',
  'gasto_bancario',
  'total',
  'varios_bebidas',
  'prestamos',
  'interes_prestamos'
]
